"use client";

import { useState, type FormEvent } from "react";
import { Search, Plus, Pencil, Trash2, MessageCircle, ClipboardList, Wallet, Clock3, CheckCircle2, UserRound, ArrowLeftRight, Inbox } from "lucide-react";
import { interpolate } from "./content";
import { useContent } from "./content-provider";
import { dateLabel, localDate, normalizePhone } from "./client";
import type { Admin, Provider, RequestRecord, Service, WorkspaceData } from "./types";
import { PageHeading, Status, type Mutate } from "./workspace";

const SCOPES = ["all", "mine", "unassigned", "others"] as const;
type Scope = typeof SCOPES[number];
function inScope(r: RequestRecord, scope: Scope, me: string) {
  if (scope === "mine") return r.ownerAdminId === me;
  if (scope === "unassigned") return !r.ownerAdminId;
  if (scope === "others") return !!r.ownerAdminId && r.ownerAdminId !== me;
  return true;
}
export function AdminRequests({ data, mutate, busy }: { data: WorkspaceData; mutate: Mutate; busy: boolean }) {
  const { c } = useContent(); const me = data.user.id;
  const [search, setSearch] = useState(""), [status, setStatus] = useState("all"), [scope, setScope] = useState<Scope>("all");
  const rows = data.requests.filter(r => inScope(r, scope, me) && (status === "all" || r.status === status) && `${r.name} ${r.reference} ${r.serviceName} ${r.phone}`.toLowerCase().includes(search.toLowerCase()));
  const scopeCount = (s: Scope) => data.requests.filter(r => inScope(r, s, me)).length;
  return <><PageHeading title="admin.title" description="admin.description" /><div className="care-metrics">{([
    ["admin.total", data.requests.length, ClipboardList], ["admin.pending", data.requests.filter(r => r.status === "pending").length, Clock3], ["admin.mineActive", data.requests.filter(r => r.ownerAdminId === me && (r.status === "approved" || r.status === "forwarded")).length, UserRound], ["admin.unassignedCount", data.requests.filter(r => !r.ownerAdminId && r.status === "pending").length, Inbox],
  ] as const).map(([label, count, Icon]) => <div className="care-metric" key={label}><span><Icon size={22} /></span><strong>{count.toLocaleString("ar-IQ")}</strong><p>{c(label)}</p></div>)}</div>
    <div className="care-scope-tabs" role="tablist">{SCOPES.map(s => <button key={s} role="tab" aria-selected={scope === s} className={scope === s ? "active" : ""} onClick={() => setScope(s)}>{c(`admin.scope.${s}`)}<span>{scopeCount(s).toLocaleString("ar-IQ")}</span></button>)}</div>
    <div className="care-filters"><label className="care-search"><Search size={19} /><input aria-label={c("common.search")} placeholder={c("admin.searchPlaceholder")} value={search} onChange={event => setSearch(event.target.value)} /></label><label>{c("common.status")}<select value={status} onChange={event => setStatus(event.target.value)}><option value="all">{c("common.all")}</option>{(["pending", "approved", "forwarded", "completed", "cancelled"] as const).map(value => <option key={value} value={value}>{c(`status.${value}`)}</option>)}</select></label></div>
    <div className="care-admin-requests">{!rows.length && <div className="care-empty"><ClipboardList size={32} /><p>{c("common.empty")}</p></div>}{rows.map(request => <AdminRequest key={request.id} request={request} providers={data.providers} admins={data.admins} me={me} mutate={mutate} busy={busy} />)}</div>
  </>;
}
function AdminRequest({ request, providers, admins, me, mutate, busy }: { request: RequestRecord; providers: Provider[]; admins: Admin[]; me: string; mutate: Mutate; busy: boolean }) {
  const { c } = useContent();
  const [providerId, setProviderId] = useState(request.providerId || ""), [amount, setAmount] = useState("");
  const [rejecting, setRejecting] = useState(false), [transferring, setTransferring] = useState(false), [reason, setReason] = useState(""), [target, setTarget] = useState(me);
  const provider = providers.find(p => p.id === (request.providerId || providerId));
  const mapUrl = request.latitude != null && request.longitude != null ? `https://www.google.com/maps?q=${request.latitude},${request.longitude}` : "";
  const locationText = [request.formattedAddress || request.address, request.locationNotes].filter(Boolean).join(" — ") || c("common.notSpecified");
  const message = provider ? interpolate(c("whatsapp.template"), { provider: provider.name, service: request.serviceName, name: request.name, phone: request.phone, address: locationText, map: mapUrl || c("common.notSpecified"), details: [request.medicine, request.details].filter(Boolean).join(" · ") || c("common.notSpecified") }) : "";
  const owned = !!request.ownerAdminId, mine = request.ownerAdminId === me;
  const canDispatch = request.status === "pending" || request.status === "approved";
  return <article className="care-dispatch"><div className="care-dispatch-info"><div className="care-card-top"><span className="care-reference" dir="ltr">{request.reference}</span><Status value={request.status} /></div>
    <div className={`care-owner ${mine ? "mine" : owned ? "other" : "none"}`}>{owned ? <>{c("admin.responsible")}: <strong>{mine ? c("admin.you") : (request.ownerAdminName || c("common.notSpecified"))}</strong></> : c("admin.unassignedBadge")}</div>
    <h2>{request.serviceName}</h2><p className="care-muted">{dateLabel(request.createdAt)}</p><dl className="care-facts"><div><dt>{c("field.name")}</dt><dd>{request.name}</dd></div><div><dt>{c("field.phone")}</dt><dd dir="ltr">{request.phone}</dd></div><div><dt>{c("field.location")}</dt><dd>{request.formattedAddress || request.address || c("common.notSpecified")}{mapUrl && <> · <a className="care-text-button" href={mapUrl} target="_blank" rel="noreferrer">{c("field.openMap")}</a></>}</dd></div>{request.locationNotes && <div><dt>{c("field.landmark")}</dt><dd>{request.locationNotes}</dd></div>}<div><dt>{c("field.gender")}</dt><dd>{c(`field.${request.gender}`)}</dd></div>{request.medicine && <div><dt>{c("pharmacy.medicine")}</dt><dd>{request.medicine}</dd></div>}<div><dt>{c("field.notes")}</dt><dd>{request.details || c("common.notSpecified")}</dd></div></dl>{request.attachment && <a className="care-text-button" href={`/api/care/attachments/${request.id}`} target="_blank" rel="noreferrer">{c("pharmacy.attachment")}</a>}</div>
    <div className="care-dispatch-actions">
      {request.status === "pending" && <div className="care-inline">{!owned && <button className="care-secondary" disabled={busy} onClick={() => void mutate({ action: "claim", id: request.id })}><Inbox size={16} />{c("admin.claim")}</button>}{(!owned || mine) && <button className="care-primary" disabled={busy} onClick={() => void mutate({ action: "approve", id: request.id })}>{c(owned ? "admin.approve" : "admin.approveTake")}</button>}<button className="care-text-button danger" disabled={busy} onClick={() => setRejecting(v => !v)}>{c("admin.reject")}</button></div>}
      {rejecting && <div className="care-delete-confirm" role="alert"><p>{c("admin.rejectConfirm")}</p><input placeholder={c("admin.reasonOptional")} value={reason} maxLength={500} onChange={e => setReason(e.target.value)} /><div className="care-inline"><button className="care-secondary danger" disabled={busy} onClick={async () => { if (await mutate({ action: "reject", id: request.id, reason })) setRejecting(false); }}>{c("admin.reject")}</button><button className="care-text-button" onClick={() => setRejecting(false)}>{c("common.cancel")}</button></div></div>}
      {owned && request.status !== "completed" && request.status !== "cancelled" && <><button className="care-secondary" disabled={busy} onClick={() => { setTarget(me); setTransferring(v => !v); }}><ArrowLeftRight size={16} />{mine ? c("admin.reassign") : c("admin.takeover")}</button>{transferring && <div className="care-delete-confirm" role="alert"><p>{interpolate(c("admin.takeoverConfirm"), { from: request.ownerAdminName || c("common.notSpecified") })}</p><label>{c("admin.transferTo")}<select value={target} onChange={e => setTarget(e.target.value)}>{admins.filter(a => a.active).map(a => <option key={a.id} value={a.id}>{a.id === me ? c("admin.you") : a.name}</option>)}</select></label><input placeholder={c("admin.reasonOptional")} value={reason} maxLength={500} onChange={e => setReason(e.target.value)} /><div className="care-inline"><button className="care-secondary" disabled={busy} onClick={async () => { if (await mutate({ action: "transfer", id: request.id, toAdmin: target, reason })) setTransferring(false); }}>{c("admin.confirmTransfer")}</button><button className="care-text-button" onClick={() => setTransferring(false)}>{c("common.cancel")}</button></div></div>}</>}
      {canDispatch && <label>{c("admin.provider")}<select value={request.providerId || providerId} onChange={event => setProviderId(event.target.value)} disabled={busy}><option value="">{c("admin.selectProvider")}</option>{providers.filter(p => p.active || p.id === request.providerId).map(p => <option key={p.id} value={p.id}>{p.name} · {c(`field.${p.gender}`)}</option>)}</select></label>}
      {canDispatch && !providers.some(p => p.active) && !provider && <p>{c("admin.noProviders")}</p>}
      {provider && <><a className="care-whatsapp" href={`https://wa.me/${provider.phone.replace(/\D/g, "")}?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer"><MessageCircle size={18} />{c("admin.whatsapp")}</a><details><summary>{c("content.preview")}</summary><p className="care-message-preview">{message}</p></details></>}
      {canDispatch && <><p className="care-help">{c("admin.forwardHint")}</p><button className="care-primary" disabled={!provider || busy} onClick={() => void mutate({ action: "forward", id: request.id, providerId })}>{c("admin.markForwarded")}</button></>}
      {request.status === "forwarded" && <button className="care-secondary" disabled={busy} onClick={() => void mutate({ action: "complete", id: request.id })}>{c("admin.complete")}</button>}
      {(request.status === "approved" || request.status === "forwarded" || request.status === "completed") && (request.paid ? <p className="care-paid"><CheckCircle2 size={18} />{c("admin.alreadyPaid")}</p> : <form onSubmit={event => { event.preventDefault(); void mutate({ action: "paid", id: request.id, amount: amount === "" ? null : Number(amount) }); }}><label>{c("admin.amount")}<input type="number" min="0" max="1000000000" step="1" value={amount} onChange={event => setAmount(event.target.value)} /></label><p className="care-help">{c("admin.paymentHint")}</p><button className="care-primary" disabled={busy}>{c("admin.recordPaid")}</button></form>)}
    </div></article>;
}

export function CatalogEditor({ kind, data, mutate, busy }: { kind: "providers" | "services"; data: WorkspaceData; mutate: Mutate; busy: boolean }) {
  const { c } = useContent(); const [editing, setEditing] = useState<Provider | Service | null>(null); const [formKey, setFormKey] = useState(0);
  const [deleting, setDeleting] = useState<string | null>(null);
  const isProvider = kind === "providers"; const rows: (Provider | Service)[] = isProvider ? data.providers : data.services;
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget);
    if (await mutate({ action: isProvider ? "provider" : "service", ...(editing ? { id: editing.id } : {}), name: form.get("name"), active: form.get("active") === "on", ...(isProvider ? { phone: normalizePhone(String(form.get("phone"))), gender: form.get("gender") } : {}) })) { setEditing(null); setFormKey(n => n + 1); }
  }
  return <><PageHeading title={`${kind}.title`} description={`${kind}.description`} /><div className="care-catalog-grid"><form key={formKey} onSubmit={event => void submit(event)} className="care-panel care-form"><h2><Plus size={20} />{c(editing ? "common.edit" : `${kind}.add`)}</h2><label>{c(`${kind}.name`)}<input name="name" defaultValue={editing?.name || ""} required minLength={2} maxLength={isProvider ? 120 : 100} /></label>{isProvider && <><label>{c("field.phone")}<input name="phone" type="tel" dir="ltr" required placeholder={c("login.phonePlaceholder")} defaultValue={editing && "phone" in editing ? editing.phone : ""} /></label><label>{c("field.gender")}<select name="gender" defaultValue={editing && "gender" in editing ? editing.gender : "female"}><option value="female">{c("field.female")}</option><option value="male">{c("field.male")}</option></select></label></>}<label className="care-checkbox"><input name="active" type="checkbox" defaultChecked={editing?.active ?? true} />{c("common.active")}</label><div className="care-inline"><button className="care-primary" disabled={busy}>{c(busy ? "common.saving" : editing ? "common.save" : "common.add")}</button>{editing && <button type="button" className="care-secondary" onClick={() => { setEditing(null); setFormKey(n => n + 1); }}>{c("common.cancel")}</button>}</div></form><div className="care-catalog-list">{!rows.length && <div className="care-empty">{c("common.empty")}</div>}{rows.map(row => <article className="care-card" key={row.id}><div className="care-card-top"><h3>{row.name}</h3><span className={`care-status ${row.active ? "completed" : "pending"}`}>{c(row.active ? "common.active" : "common.inactive")}</span></div>{"phone" in row && <p className="care-muted" dir="ltr">{row.phone}</p>}<div className="care-inline"><button className="care-secondary" onClick={() => { setEditing(row); setFormKey(n => n + 1); }}><Pencil size={15} />{c("common.edit")}</button><button className="care-text-button danger" onClick={() => setDeleting(row.id)}><Trash2 size={15} />{c("common.delete")}</button></div>{deleting === row.id && <div className="care-delete-confirm" role="alert"><p>{c(`${kind}.deleteConfirm`)}</p><div className="care-inline"><button disabled={busy} className="care-secondary danger" onClick={async () => { if (await mutate({ action: "delete", kind: isProvider ? "provider" : "service", id: row.id })) setDeleting(null); }}>{c("common.delete")}</button><button className="care-text-button" onClick={() => setDeleting(null)}>{c("common.cancel")}</button></div></div>}</article>)}</div></div></>;
}

export function Accounting({ data }: { data: WorkspaceData }) {
  const { c } = useContent(); const [search, setSearch] = useState(""), [provider, setProvider] = useState(""), [from, setFrom] = useState(""), [to, setTo] = useState("");
  const rows = data.payments.filter(p => {
    const date = localDate(p.requestDate);
    return (!provider || p.providerId === provider) && (!from || date >= from) && (!to || date <= to) && `${p.reference} ${p.serviceName} ${p.providerName}`.toLowerCase().includes(search.toLowerCase());
  });
  return <><PageHeading title="accounting.title" description="accounting.description" /><div className="care-account-summary"><div><span>{c("accounting.total")}</span><strong>{rows.reduce((total, p) => total + (p.amount ?? 0), 0).toLocaleString("ar-IQ")} <small>{c("common.currency")}</small></strong></div><div><span>{c("accounting.count")}</span><strong>{rows.length.toLocaleString("ar-IQ")}</strong></div><Wallet size={40} /></div><div className="care-filters"><label className="care-search"><Search size={19} /><input aria-label={c("common.search")} placeholder={c("accounting.searchPlaceholder")} value={search} onChange={event => setSearch(event.target.value)} /></label><label>{c("admin.provider")}<select value={provider} onChange={event => setProvider(event.target.value)}><option value="">{c("common.all")}</option>{data.providers.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>{c("common.dateFrom")}<input type="date" max={to || undefined} value={from} onChange={event => setFrom(event.target.value)} /></label><label>{c("common.dateTo")}<input type="date" min={from || undefined} value={to} onChange={event => setTo(event.target.value)} /></label></div><div className="care-table-wrap"><table><thead><tr>{(["common.reference", "common.date", "field.service", "admin.provider", "common.status", "accounting.amount", "accounting.paidAt"] as const).map(key => <th key={key}>{c(key)}</th>)}</tr></thead><tbody>{rows.map(row => <tr key={row.id}><td dir="ltr">{row.reference}</td><td>{dateLabel(row.requestDate)}</td><td>{row.serviceName}</td><td>{row.providerName}</td><td><span className="care-status completed">{c("status.paid")}</span></td><td>{row.amount === null ? c("common.notSpecified") : `${row.amount.toLocaleString("ar-IQ")} ${c("common.currency")}`}</td><td>{dateLabel(row.paidAt)}</td></tr>)}</tbody></table>{!rows.length && <div className="care-empty">{c("common.empty")}</div>}</div></>;
}
