export const defaultContent = {
  "brand.name": "Life Line",
  "brand.tagline": "الخدمات الطبية المنزلية",
  "brand.footer": "الرعاية تبدأ بالاهتمام",
  "brand.rights": "جميع الحقوق محفوظة لشركة VITAL",
  "login.welcome": "أهلاً بعودتك",
  "login.title": "رعايتك تبدأ من هنا",
  "login.description": "سجّل دخولك لطلب خدمة طبية منزلية أو دواء، ومتابعة طلباتك في مكان واحد.",
  "login.choose": "اختر طريقة الدخول",
  "login.email": "البريد الإلكتروني",
  "login.whatsapp": "رقم واتساب",
  "login.emailPlaceholder": "name@example.com",
  "login.phonePlaceholder": "+964 7XX XXX XXXX",
  "login.emailHint": "سنرسل رمزاً إلى بريدك الإلكتروني لتسجيل الدخول.",
  "login.phoneHint": "أدخل رقمك بصيغته الدولية، مع رمز البلد.",
  "login.send": "إرسال رمز الدخول",
  "login.verify": "تأكيد الرمز والدخول",
  "login.code": "رمز التحقق",
  "login.codeHint": "أدخل الرمز الذي وصلك. لا تشاركه مع أي شخص.",
  "login.sent": "تم طلب إرسال الرمز. تحقق من بريدك أو واتساب.",
  "login.change": "تغيير البريد أو الرقم",
  "login.resend": "إعادة إرسال الرمز",
  "login.passwordChannel": "بريد وكلمة مرور",
  "login.password": "كلمة المرور",
  "login.passwordSubmit": "تسجيل الدخول",
  "login.passwordHint": "أدخل البريد وكلمة المرور. مخصّص للحسابات التجريبية.",
  "login.noPassword": "دخول آمن، دون كلمة مرور",
  "login.privacy": "رمز التحقق خاص بك وحدك. لا تشاركه مع أي شخص.",
  "login.asideLabel": "رعاية أقرب إليك",
  "login.asideTitle": "في بيتك. وبين أهلك.",
  "login.asideDescription": "اطلب الرعاية التي تحتاجها، ودع تنسيق التفاصيل علينا.",
  "login.medicalTitle": "خدمات طبية منزلية",
  "login.medicalDescription": "سحب دم، تحاليل وتضميد جروح",
  "login.pharmacyTitle": "طلبات الصيدلية",
  "login.pharmacyDescription": "أرفق الوصفة أو صورة الدواء",
  "login.asideFooter": "طلبك، تفاصيله، ومتابعته في مكان واحد",
  "demo.title": "معاينة محلية ببيانات تجريبية فقط",
  "demo.patient": "تجربة المريض",
  "demo.admin": "تجربة المدير",
  "demo.notice": "وضع تجريبي محلي — لا تدخل بيانات مرضى حقيقية",
  "nav.home": "الرئيسية",
  "nav.medical": "طلب خدمة طبية",
  "nav.pharmacy": "الصيدلية",
  "nav.requests": "طلباتي",
  "nav.profile": "حسابي",
  "nav.admin": "لوحة المدير",
  "nav.providers": "مقدمو الخدمة",
  "nav.services": "إدارة الخدمات",
  "nav.content": "النصوص والهوية",
  "nav.accounting": "سجل الحسابات",
  "nav.clients": "العملاء",
  "nav.admins": "حسابات المدراء",
  "nav.backup": "النسخ الاحتياطي",
  "nav.logout": "تسجيل الخروج",
  "nav.patient": "واجهة المريض",
  "nav.adminLogin": "دخول الإدارة",
  "common.loading": "جارٍ التحميل…",
  "common.saving": "جارٍ الحفظ…",
  "common.save": "حفظ التغييرات",
  "common.saved": "حُفظت التغييرات بنجاح",
  "common.cancel": "إلغاء",
  "common.edit": "تعديل",
  "common.delete": "حذف",
  "common.add": "إضافة",
  "common.active": "مفعّل",
  "common.inactive": "متوقف",
  "common.all": "الكل",
  "common.search": "بحث",
  "common.empty": "لا توجد نتائج مطابقة",
  "common.retry": "إعادة المحاولة",
  "common.back": "رجوع",
  "common.optional": "اختياري",
  "common.currency": "د.ع",
  "common.notSpecified": "غير محدد",
  "common.dateFrom": "من تاريخ",
  "common.dateTo": "إلى تاريخ",
  "common.status": "الحالة",
  "common.date": "تاريخ الطلب",
  "common.reference": "رقم الطلب",
  "common.details": "التفاصيل",
  "common.actions": "الإجراءات",
  "home.eyebrow": "رعايتك، على راحتك",
  "home.title": "كيف نقدر نساعدك اليوم؟",
  "home.description": "اختر الخدمة المناسبة، وسنتولى تنسيق طلبك مع مقدم الخدمة.",
  "home.medicalDescription": "كادر طبي لزيارتك في المنزل، حسب الخدمة والتفضيل الذي تختاره.",
  "home.pharmacyDescription": "اكتب اسم الدواء أو أرفق صورة الوصفة، واترك لنا تنسيق الطلب.",
  "home.request": "ابدأ طلبك",
  "home.latest": "آخر طلباتك",
  "home.viewAll": "عرض جميع الطلبات",
  "home.empty": "لم تطلب خدمة بعد",
  "home.emptyHint": "ستجد هنا حالة طلباتك وتفاصيلها بعد إرسالها.",
  "profile.title": "بياناتك الأساسية",
  "profile.description": "احفظ بيانات التواصل والعنوان لتسهيل طلب الخدمات لاحقاً.",
  "field.name": "الاسم الكامل",
  "field.phone": "رقم الهاتف",
  "field.address": "العنوان التفصيلي",
  "field.namePlaceholder": "اكتب اسم مقدم الطلب",
  "field.addressPlaceholder": "المدينة، المنطقة، الشارع وأقرب نقطة دالة",
  "field.details": "تفاصيل إضافية عن الحالة",
  "field.notes": "ملاحظات إضافية",
  "field.notesPlaceholder": "أضف ما يساعدنا على تجهيز طلبك",
  "field.service": "نوع الخدمة",
  "field.selectService": "اختر الخدمة المطلوبة",
  "field.gender": "تفضيل الكادر الطبي",
  "field.male": "رجالي",
  "field.female": "نسائي",
  "field.any": "دون تفضيل",
  "field.location": "موقع الخدمة على الخريطة",
  "field.locationHint": "اضغط على الخريطة لتحديد موقع الزيارة بدقّة، أو استخدم زر موقعي الحالي.",
  "field.useMyLocation": "استخدام موقعي الحالي",
  "field.locating": "جارٍ تحديد الموقع…",
  "field.selectedLocation": "الموقع المحدد",
  "field.locationRequired": "يرجى تحديد موقع الخدمة على الخريطة قبل الإرسال.",
  "field.locationDenied": "تعذّر الوصول إلى موقعك. يمكنك تحديد الموقع يدوياً على الخريطة.",
  "field.landmark": "أقرب نقطة دالة أو وصف للموقع",
  "field.landmarkPlaceholder": "مثال: قرب صيدلية الرازي، الشارع الثاني بعد الجامع، البيت المقابل للمدرسة",
  "field.coordinates": "الإحداثيات",
  "field.openMap": "فتح الموقع على الخريطة",
  "field.patientGender": "جنس مقدم الطلب",
  "field.age": "العمر",
  "field.agePlaceholder": "مثال: 45",
  "request.title": "طلب خدمة طبية منزلية",
  "request.description": "أخبرنا بما تحتاجه، وسيتولى المدير تنسيق الزيارة المناسبة.",
  "request.contact": "بيانات التواصل والزيارة",
  "request.serviceDetails": "تفاصيل الخدمة",
  "request.submit": "إرسال الطلب",
  "request.success": "وصل طلبك بنجاح",
  "request.successHint": "تم استلام طلبك وسيتم التواصل معك بعد مراجعة الطلب.",
  "request.view": "متابعة طلباتي",
  "request.consent": "أوافق على مشاركة بيانات هذا الطلب مع مقدم الخدمة عبر واتساب لتنسيق الرعاية.",
  "request.noServices": "لا توجد خدمات متاحة حالياً. يرجى المحاولة لاحقاً.",
  "pharmacy.title": "طلب دواء من الصيدلية",
  "pharmacy.description": "أضف اسم الدواء أو صورة واضحة للوصفة الطبية.",
  "pharmacy.medicine": "اسم الدواء (اختياري)",
  "pharmacy.medicinePlaceholder": "اسم الدواء والتركيز، إن عُرف",
  "pharmacy.upload": "صورة الدواء أو الوصفة",
  "pharmacy.uploadHint": "صورة JPEG أو PNG أو WebP، بحد أقصى ٥ ميغابايت. تحفظ بشكل خاص.",
  "pharmacy.chooseFile": "اختيار صورة",
  "pharmacy.removeFile": "إزالة الصورة",
  "pharmacy.attachment": "عرض المرفق الخاص",
  "requests.title": "طلباتك، خطوة بخطوة",
  "requests.description": "تابع حالة الطلب وراجع تفاصيل الخدمة من هنا.",
  "status.pending": "قيد الانتظار",
  "status.approved": "موافَق عليه",
  "status.forwarded": "محوّل",
  "status.completed": "منجز",
  "status.cancelled": "ملغى",
  "status.paid": "مدفوع",
  "admin.title": "كل الطلبات، في مكان واحد",
  "admin.description": "راجع الطلبات الواردة، اختر مقدم الخدمة، وتابع التنفيذ والدفع.",
  "admin.total": "إجمالي الطلبات",
  "admin.pending": "بانتظار المراجعة",
  "admin.forwarded": "طلبات محوّلة",
  "admin.paid": "خدمات مدفوعة",
  "admin.searchPlaceholder": "ابحث بالاسم أو رقم الطلب أو الخدمة",
  "admin.provider": "مقدم الخدمة",
  "admin.selectProvider": "اختر مقدم الخدمة",
  "admin.whatsapp": "فتح رسالة واتساب",
  "admin.markForwarded": "تأكيد تحويل الطلب",
  "admin.forwardHint": "بعد إرسال الرسالة في واتساب، أكّد التحويل هنا. فتح الرسالة وحده لا يغيّر حالة الطلب.",
  "admin.complete": "تسجيل إنجاز الخدمة",
  "admin.recordPaid": "تأكيد القبول وتسجيل الدفع",
  "admin.paymentHint": "استخدم هذا الإجراء بعد موافقة مقدم الخدمة وتحققك من استلام الدفع.",
  "admin.amount": "المبلغ بالدينار العراقي (اختياري)",
  "admin.alreadyPaid": "تم تسجيل الدفع لهذا الطلب",
  "admin.noProviders": "أضف مقدم خدمة أولاً من قسم مقدمي الخدمة.",
  "admin.mineActive": "طلباتي النشطة",
  "admin.unassignedCount": "طلبات غير مُسندة",
  "admin.scope.all": "كل الطلبات",
  "admin.scope.mine": "طلباتي",
  "admin.scope.unassigned": "غير مُسندة",
  "admin.scope.others": "طلبات مدراء آخرين",
  "admin.responsible": "المسؤول",
  "admin.you": "أنت",
  "admin.unassignedBadge": "غير مُسند بعد",
  "admin.claim": "استلام الطلب",
  "admin.approve": "الموافقة",
  "admin.approveTake": "موافقة واستلام",
  "admin.reject": "رفض الطلب",
  "admin.rejectConfirm": "هل تريد رفض هذا الطلب؟ يمكنك إضافة سبب (اختياري).",
  "admin.reasonOptional": "السبب (اختياري)",
  "admin.takeover": "نقل المسؤولية إليّ",
  "admin.reassign": "إعادة الإسناد",
  "admin.takeoverConfirm": "هل تريد نقل مسؤولية هذا الطلب من {from}؟",
  "admin.transferTo": "نقل المسؤولية إلى",
  "admin.confirmTransfer": "تأكيد النقل",
  "providers.title": "مقدمو الخدمة",
  "providers.description": "أدر قائمة الكادر الطبي والصيدليات وأرقام التواصل.",
  "providers.name": "اسم مقدم الخدمة",
  "providers.add": "إضافة مقدم خدمة",
  "providers.deleteConfirm": "هل تريد حذف مقدم الخدمة؟ إذا كان مرتبطاً بطلب سابق فسيتوقف فقط حفاظاً على السجلات.",
  "services.title": "الخدمات المتاحة",
  "services.description": "أضف الخدمات أو عدّل أسماءها دون تغيير الكود.",
  "services.name": "اسم الخدمة",
  "services.add": "إضافة خدمة",
  "services.deleteConfirm": "هل تريد حذف الخدمة؟ الخدمات المرتبطة بطلبات سابقة ستتوقف فقط.",
  "content.title": "كلمات المنصة، بأسلوبك",
  "content.description": "عدّل العناوين والأزرار والرسائل والهوية. تظهر التعديلات لجميع المستخدمين بعد الحفظ.",
  "content.searchPlaceholder": "ابحث عن عبارة أو مفتاح نص",
  "content.original": "النص الأصلي",
  "content.preview": "معاينة النص",
  "content.restore": "استعادة الأصل",
  "content.unsaved": "لديك تعديلات لم تُحفظ",
  "content.group": "القسم",
  "content.whatsappHint": "احتفظ بمتغيرات القالب: {provider} و{service} و{name} و{phone} و{address} و{details}. المتغير {map} اختياري ويضيف رابط الخريطة.",
  "content.group.brand": "الهوية",
  "content.group.login": "تسجيل الدخول",
  "content.group.demo": "المعاينة المحلية",
  "content.group.nav": "التنقل",
  "content.group.common": "عبارات مشتركة",
  "content.group.home": "الرئيسية",
  "content.group.profile": "الحساب",
  "content.group.field": "حقول النماذج",
  "content.group.request": "طلب الخدمة",
  "content.group.pharmacy": "الصيدلية",
  "content.group.requests": "متابعة الطلبات",
  "content.group.status": "حالات الطلب والدفع",
  "content.group.admin": "إدارة الطلبات",
  "content.group.providers": "مقدمو الخدمة",
  "content.group.services": "إدارة الخدمات",
  "content.group.content": "محرر النصوص",
  "content.group.accounting": "الحسابات",
  "content.group.clients": "العملاء",
  "content.group.admins": "حسابات المدراء",
  "content.group.backup": "النسخ الاحتياطي",
  "content.group.public": "الواجهة العامة",
  "content.group.adminLogin": "دخول الإدارة",
  "content.group.whatsapp": "رسالة واتساب",
  "content.group.error": "رسائل التنبيه",
  "accounting.title": "سجل الحسابات",
  "accounting.description": "سجل الخدمات المدفوعة مع البحث حسب تاريخ الطلب ومقدم الخدمة.",
  "accounting.total": "مجموع المبالغ المسجّلة",
  "accounting.count": "خدمات مدفوعة ضمن النتائج",
  "accounting.amount": "المبلغ",
  "accounting.paidAt": "تاريخ الدفع",
  "accounting.searchPlaceholder": "ابحث بالخدمة أو مقدمها أو رقم الطلب",
  "clients.title": "العملاء",
  "clients.description": "ابحث عن العميل برقم الهاتف أو الاسم واستعرض تقريره الكامل.",
  "clients.search": "بحث",
  "clients.searchPlaceholder": "رقم الهاتف أو الاسم",
  "clients.requests": "طلب",
  "clients.noResults": "لا يوجد عميل مطابق.",
  "clients.report": "عرض التقرير",
  "clients.print": "طباعة التقرير",
  "clients.lastRequest": "آخر طلب",
  "clients.age": "العمر",
  "clients.gender": "الجنس",
  "admins.title": "حسابات المدراء",
  "admins.description": "الحسابات الإدارية الخمسة وحالتها وعدد طلباتها.",
  "admins.name": "الاسم",
  "admins.username": "اسم المستخدم",
  "admins.status": "الحالة",
  "admins.lastLogin": "آخر دخول",
  "admins.activeRequests": "طلبات نشطة",
  "admins.completedRequests": "طلبات منجزة",
  "admins.never": "لم يسجّل دخولاً بعد",
  "admins.changePassword": "تغيير كلمة المرور",
  "admins.newPassword": "كلمة المرور الجديدة",
  "admins.passwordChanged": "تم تغيير كلمة المرور بنجاح.",
  "admins.passwordSubmit": "حفظ كلمة المرور",
  "admins.passwordShort": "كلمة المرور يجب أن تكون 8 أحرف على الأقل.",
  "admins.selfNote": "يغيّر كل مدير كلمة مروره الخاصة من هنا.",
  "backup.title": "النسخ الاحتياطي",
  "backup.description": "أنشئ نسخة احتياطية من بيانات النظام وحمّلها.",
  "backup.create": "إنشاء وتحميل نسخة احتياطية",
  "backup.generatedAt": "أُنشئت النسخة في",
  "backup.excludes": "لا تتضمن النسخة كلمات المرور أو الرموز أو الأسرار.",
  "public.noAccount": "لا حاجة لإنشاء حساب — قدّم طلبك مباشرة وسنتواصل معك.",
  "public.referenceLabel": "رقم طلبك",
  "public.pendingStatus": "قيد المراجعة",
  "public.backHome": "العودة للرئيسية",
  "public.newRequest": "طلب جديد",
  "adminLogin.badge": "منطقة الإدارة",
  "adminLogin.title": "تسجيل دخول الإدارة",
  "adminLogin.description": "هذه المنطقة مخصّصة لفريق الإدارة فقط. أدخل اسم المستخدم وكلمة المرور.",
  "adminLogin.username": "اسم المستخدم",
  "adminLogin.usernamePlaceholder": "admin1",
  "adminLogin.password": "كلمة المرور",
  "adminLogin.remember": "إبقائي مسجّلاً للدخول",
  "adminLogin.submit": "دخول لوحة الإدارة",
  "adminLogin.security": "الدخول محمي عبر جلسة آمنة. لا تشارك بيانات دخولك.",
  "adminLogin.back": "العودة إلى الموقع العام",
  "adminLogin.asideTitle": "لوحة عمليات موحّدة",
  "adminLogin.asideDescription": "راجع الطلبات الواردة، وزّع المسؤولية، وتابع مقدمي الخدمة من مكان واحد.",
  "adminLogin.asideOwnershipTitle": "مسؤولية واضحة",
  "adminLogin.asideOwnershipDescription": "كل طلب يظهر لجميع المدراء مع مدير مسؤول واحد.",
  "adminLogin.asideSecureTitle": "وصول آمن",
  "adminLogin.asideSecureDescription": "دخول الإدارة فقط. لا يملك العملاء أي حساب.",
  "whatsapp.template": "مرحباً {provider}، يوجد طلب جديد: {service} لصالح {name} - رقم التواصل: {phone} - الموقع: {address} - الخريطة: {map} - التفاصيل: {details} - يرجى التأكيد ✅",
  "error.INVALID": "يرجى التأكد من صحة البيانات وإكمال الحقول المطلوبة.",
  "error.PHONE": "أدخل رقم الهاتف بصيغته الدولية مع رمز البلد، مثل +964.",
  "error.UNAUTHORIZED": "انتهت الجلسة. يرجى تسجيل الدخول مجدداً.",
  "error.FORBIDDEN": "ليس لديك صلاحية لهذا الإجراء.",
  "error.UNAVAILABLE": "الخدمة غير متاحة الآن. حاول مرة أخرى لاحقاً.",
  "error.AUTH_CONFIG": "إرسال رموز التحقق غير مفعّل بعد. يرجى التواصل مع مدير المنصة.",
  "error.OTP": "تعذّر تأكيد الرمز. تحقق منه أو اطلب رمزاً جديداً.",
  "error.CREDENTIALS": "البريد الإلكتروني أو كلمة المرور غير صحيحة.",
  "error.RATE_LIMIT": "محاولات كثيرة. انتظر قليلاً ثم حاول مجدداً.",
  "error.NOT_FOUND": "لم يُعثر على السجل المطلوب.",
  "error.CONFLICT": "تغيّر السجل أو سُجّل الإجراء سابقاً. حدّث الصفحة ثم حاول مجدداً.",
  "error.FILE": "اختر صورة JPEG أو PNG أو WebP صالحة لا تتجاوز ٥ ميغابايت.",
  "error.MEDICINE": "أدخل اسم الدواء أو أرفق صورة للوصفة.",
  "error.TEMPLATE": "قالب واتساب يجب أن يتضمن جميع المتغيرات المطلوبة.",
  "error.NETWORK": "تعذّر الاتصال. بيانات النموذج ما زالت هنا؛ حاول مرة أخرى.",
} as const;

export type ContentKey = keyof typeof defaultContent;
export type ContentMap = Record<ContentKey, string>;
export type ContentState = { values: ContentMap; revision: number };
export function interpolate(template: string, values: Record<string, string>) {
  return template.replace(/\{(\w+)\}/g, (match, key: string) => values[key] ?? match);
}
